spring:
  cloud:
    stream:
      bindings:
        in:
          consumer:
            partitioned: true
          destination: stream
          group: sc
        all:
          destination: stream
          group: sca
      instance-count: 2
      instance-index: 1
logging:
  level:
    com.suimi.hello: debug
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%10.10t]){magenta} %clr(%-40.40logger{39}.%-10.25M{25}){cyan} %clr(:){faint} %m%n"
server:
  port: 8081
