spring:
  rabbitmq:
    host: 192.168.6.164
    port: 5672
    username: user
    password: pwd
  cloud:
    stream:
      rabbit:
        bindings:
          in:
            consumer:
              bindQueue: true
              bindingRoutingKey: test.#.
          all:
            consumer:
              bindQueue: true
              bindingRoutingKey: all.#
