spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.6.164:32790,192.168.6.164:32791,192.168.6.164:32792
          zk-nodes: 192.168.6.164:2188
        bindings:
          in:
            consumer:
              resetOffsets: true
              startOffset: latest
